sections:
  - title: "ğŸš€ Features"
    labels: ["feature"]
  - title: "ğŸ› Bug Fixes"
    labels: ["fix"]
  - title: "ğŸ§° Maintenance"
    labels: ["chore", "refactor"]

template: ./CHANGELOG.tpl.md